name: Manual update of data
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: update
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "8"
      - run: npm ci
      - run: npm run update
      - uses: EndBug/add-and-commit@v7
        with:
          add: "data/*"
          default_author: github_actor
          message: "Manual update of data"
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ github.token }}
